### ISSUE TITLE
插件相关问题

### ISSUE THREAD

**Issue by zhuhu00** [Xuer04/Awesome-neovim#3]
非常感谢你所提供的配置，基本上使用成功了，但是有几个问题不知道怎么解决：
1. `nvim .`时候，会出现这个问题， copilot_cmp中已经用github账号验证过了，能够使用，但是这个问题想请教下。如何解决，还有一个是LspAttach的那个。
<img width="1118" alt="image" src="https://github.com/cxzhou35/Awesome-neovim/assets/29742046/ed2b8ab2-055b-48bc-bd45-0109f87a5061">
2. Joshuto不能正常使用，这里疑惑是不是需要安装好Joshuto的配置？输入`:Joshuto`会显示`Please install joshuto. Check documentation for more information`，虽然输入的时候，`Joshuto`能自动补全，显示有这个命令。
使用的终端是mac m1 pro. 期待能帮忙解答下。

**Comment by cxzhou35** [comment]
非常感谢提出这个issue！

1. 问题一
- 第一个 error 我也遇到了，目前还不知道怎么解决，这个报错不太稳定，大部分出现的场景是在我从一个file type 切换到另一个 file type的时候，我会在[copilot-cmp](https://github.com/zbirenbaum/copilot-cmp/issues)里去找找解决办法。

- 第二个 error 同样也是 copilot-cmp 这个插件的问题。

2. 问题二

   是的，你需要先安装一下 [Joshuto](https://github.com/kamiyaa/joshuto)，安装完之后需要重新加载一下插件。

**Comment by cxzhou35** [comment]
我在 copilot-cmp 这个插件的仓库里也发现了类似的 issue，https://github.com/zbirenbaum/copilot-cmp/issues/70

**Comment by zhuhu00** [comment]
非常感谢，Joshuto的已经解决了。第二个好像得多看看了。
